// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTBJ6PoMh46Muzs8BSSSiWsJYgrfAQwoM',
    appId: '1:1065339553754:web:6b12455d2857c8819de2e3',
    messagingSenderId: '1065339553754',
    projectId: 'ucap-d754e',
    authDomain: 'ucap-d754e.firebaseapp.com',
    storageBucket: 'ucap-d754e.firebasestorage.app',
    measurementId: 'G-RSEKH9PJX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS4f6obOS6TIWO9GN32BOuh2r0mTyP8mc',
    appId: '1:1065339553754:android:c43171f9e64312439de2e3',
    messagingSenderId: '1065339553754',
    projectId: 'ucap-d754e',
    storageBucket: 'ucap-d754e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDddwXmWZC-2OPZdMBS5zFWzJLeOozr9cE',
    appId: '1:1065339553754:ios:7b937ed5a2de445a9de2e3',
    messagingSenderId: '1065339553754',
    projectId: 'ucap-d754e',
    storageBucket: 'ucap-d754e.firebasestorage.app',
    iosBundleId: 'com.example.gh6Ucap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDddwXmWZC-2OPZdMBS5zFWzJLeOozr9cE',
    appId: '1:1065339553754:ios:7b937ed5a2de445a9de2e3',
    messagingSenderId: '1065339553754',
    projectId: 'ucap-d754e',
    storageBucket: 'ucap-d754e.firebasestorage.app',
    iosBundleId: 'com.example.gh6Ucap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTBJ6PoMh46Muzs8BSSSiWsJYgrfAQwoM',
    appId: '1:1065339553754:web:5047c592d1c176099de2e3',
    messagingSenderId: '1065339553754',
    projectId: 'ucap-d754e',
    authDomain: 'ucap-d754e.firebaseapp.com',
    storageBucket: 'ucap-d754e.firebasestorage.app',
    measurementId: 'G-55D1XTY978',
  );
}
